import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const templates = JSON.parse(readFileSync('templates.json', 'utf-8'));

const rows = templates.map(t => {
  const url = `https://github.com/LegionEdge/sandbox-templates/tree/main/${t.path}`;
  return `| [${t.title}](${url}) | ${t.description || ''} |`;
});

const table = [
  '## Templates',
  '',
  '| Title | Description |',
  '|------|-------------|',
  ...rows,
  ''
].join('\n');

const intro = `
# LegionEdge Sandbox Templates

This repo includes starter templates. This section is autogenerated from \`templates.json\`.
`;

const content = `${intro.trim()}\n\n${table}`;
writeFileSync('README.md', content);
