name: Update README with templates

on:
  push:
    paths:
      - 'templates.json'
      - '.github/**/*.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate README
        run: node .github/scripts/generate-readme.js

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-update README with template links"
          file_pattern: README.md
